# Torchbear configuration - fields have been set with their default values

[web-server]
address = "0.0.0.0"
port = "3000"

[general]
init = "lighttouch-base/init.lua"
theme = "base-theme"
sitename = "Lighttouch"
slideshow = "c800a360-d198-4a87-877e-b353f7dd0a9d"

#[paths]
content = "content"
log_path = "log/torchbear"
templates_path = "templates/**/*"  # expected by lib.rs
files_path = "files"

#[log]
# minimum level to appear: error, warn, info, debug or trace
log_level = "info"

#[markdown] # https://docs.rs/comrak/newest/comrak/struct.ComrakOptions.html
ext_header_ids = 1

#[yaml]
# strict = 1 # https://github.com/chyh1990/yaml-rust/issues/102
